title: Material for students
email: jmontejo@cern.ch
description: >- # this means to ignore newlines until "baseurl:"
  Collection of material to help students in getting started with their projects.

baseurl: "/jmontejo/students" # the subpath of your site, e.g. /blog
url: "https://jmontejo.web.cern.ch" # the base hostname & protocol for your site, e.g. http://example.com
gitlab_username:  jmontejo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  start:
    output: true
  rpvmj:
    output: true
  multib:
    output: true

navigation:
  - name: Getting started
    link: /jmontejo/students/start.html
  - name: RPV MJ
    link: /jmontejo/students/rpvmj.html
  - name: Multi-b
    link: /jmontejo/students/multib.html

paginate: 3
paginate_path: "/blog/page:num/"
